@startuml layers
ditaa
+-+ +-----------------------+ +---------------------------------+
| | |        USB Cable      | |                                 |
| | +-----------------------+ |                                 |
| |                           |         Transmit signals        |
|H| +-----------------------+ |                                 |
|A| |      USB port         | |                                 |
|R| +-----------------------+ +---------------------------------+
|D|
|W| +-----------------------+ +---------------+ +---------------+
|A| |                       | |  Send signals | |Receive signals|
|R| |                       | +---------------+ +---------------+
|E| |    USB controller     |
| | |                       | +---------------+ +---------------+
+-+ +-----------------------+ |               | |               |
                              |               | |               |
+-+ +-----------------------+ |Data -> Signals| |Signals -> Data|
| | |        Driver         | |               | |               |
| | +-----------------------+ +---------------+ +---------------+
| |
| | +-+ +-------------------+ +---------------+ +---------------+
| | | | |                   | |Outgoing buffer| |Incoming buffer|
| | | | |                   | +---------------+ +---------------+
| | | | |      pySerial     |
| | | | |                   | +---------------------------------+
| | | | |                   | |     Read / write stream API     |
| | | | +-------------------+ +---------------------------------+
| | | |
| | | | +-+ +---------------+ +---------------+ +---------------+
|S| | | | | |               | | Send packets  | |Receive packets|
|O| |P| | | |               | +---------------+ +---------------+
|F| |Y| | | |               |
|T| |T| | | |serial_port_com| +---------------+ +---------------+
|W| |H| |c| |               | | COBS encoding | | COBS decoding |
|A| |O| |o| |               | +---------------+ +---------------+
|R| |N| |m| |               |
|E| | | | | |               | +---------------+ +---------------+
| | | | |l| +---------------+ |Structured data| | Bytestring -> |
| | | | |i|                   | -> bytestring | |structured data|
| | | | |b| +---------------+ |   convertion  | |   convertion  |
| | | | | | | serialization | +---------------+ +---------------+
| | | | | | +---------------+
| | | | | |                   +---------------------------------+
| | | | | |                   |    Abstraction layer OOP API    |
| | | | +-+                   +---------------------------------+
| | | |
| | | | +-------------------+ +---------------------------------+
| | | | |  Client software  | |    Structured data processing   |
+-+ +-+ +-------------------+ +---------------------------------+
@enduml