!$SERNULL = "v2"

!if %not(%variable_exists("$CLASSES"))
    !include ../Templates/Classes2.cuml
!endif

class SerNULL {
    ---
    ..private class methods..
    - $static_method("_checkObjectContent", "Data") : type A -> None
    - $static_method("_parseBuffer", "Data, BigEndian = None") : bytes /, bool OR None/ -> None
    - $static_method("_checkDefinition") : None -> None
    ..special instance methods..
    __init__(Data = None): /type A/ -> None
    ..public class methods..
    + $static_method("getSize") : None -> 0
    ..public instance methods..
    + getNative(): None -> None
    + packBytes(): None -> bytes('')
}